# Generated by Django 5.2.6 on 2025-09-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/movies/', verbose_name='Plakat'),
        ),
    ]
