# Generated by Django 5.2.6 on 2025-09-28 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/', verbose_name='Plakat'),
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Godzina rozpoczęcia')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena biletu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='api.movie')),
            ],
            options={
                'verbose_name': 'Seans',
                'verbose_name_plural': 'Seanse',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(verbose_name='Numer rzędu')),
                ('seat_number', models.IntegerField(verbose_name='Numer miejsca')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywne miejsce')),
            ],
            options={
                'verbose_name': 'Miejsce',
                'verbose_name_plural': 'Miejsca',
                'ordering': ['row_number', 'seat_number'],
                'unique_together': {('row_number', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Oczekująca'), ('confirmed', 'Potwierdzona'), ('paid', 'Opłacona'), ('cancelled', 'Anulowana')], default='pending', max_length=20)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.screening')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seat')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
                'ordering': ['-booking_time'],
                'unique_together': {('screening', 'seat')},
            },
        ),
    ]
